insert into Division (id, name) values (1, 'Ayeyarwady Region');
insert into Division (id, name) values (2, 'Bago Region');
insert into Division (id, name) values (3, 'Chin State');
insert into Division (id, name) values (4, 'Kachin State');
insert into Division (id, name) values (5, 'Kayah State');
insert into Division (id, name) values (6, 'Kayin State');
insert into Division (id, name) values (7, 'Magway Region');
insert into Division (id, name) values (8, 'Mandalay Region');
insert into Division (id, name) values (9, 'Mon State');
insert into Division (id, name) values (10, 'Naypyidaw Union Territory');
insert into Division (id, name) values (11, 'Rakhine State');
insert into Division (id, name) values (12, 'Sagaing Region');
insert into Division (id, name) values (13, 'Shan State');
insert into Division (id, name) values (14, 'Tanintharyi Region');
insert into Division (id, name) values (15, 'Yangon Region');

insert into Township (division_id, name) values(15, 'Botataung Township');
insert into Township (division_id, name) values(15, 'Dagon Seikkan Township');
insert into Township (division_id, name) values(15, 'East Dagon Township');
insert into Township (division_id, name) values(15, 'North Dagon Township');
insert into Township (division_id, name) values(15, 'North Okkalapa Township');
insert into Township (division_id, name) values(15, 'Pazundaung Township');
insert into Township (division_id, name) values(15, 'South Dagon Township');
insert into Township (division_id, name) values(15, 'South Okkalapa Township');
insert into Township (division_id, name) values(15, 'Thingangyun Township');
insert into Township (division_id, name) values(15, 'Dawbon Township');
insert into Township (division_id, name) values(15, 'Mingala Taungnyunt Township');
insert into Township (division_id, name) values(15, 'Tamwe Township');
insert into Township (division_id, name) values(15, 'Thaketa Township');
insert into Township (division_id, name) values(15, 'Yankin Township');
insert into Township (division_id, name) values(15, 'Hlaingthaya Township');
insert into Township (division_id, name) values(15, 'Insein Township');
insert into Township (division_id, name) values(15, 'Mingaladon Township');
insert into Township (division_id, name) values(15, 'Shwepyitha Township');
insert into Township (division_id, name) values(15, 'Hlegu Township');
insert into Township (division_id, name) values(15, 'Hmawbi Township');
insert into Township (division_id, name) values(15, 'Htantabin Township');
insert into Township (division_id, name) values(15, 'Taikkyi Township');
insert into Township (division_id, name) values(15, 'Dala Township');
insert into Township (division_id, name) values(15, 'Seikkyi Kanaungto Township');
insert into Township (division_id, name) values(15, 'Cocokyun Township');
insert into Township (division_id, name) values(15, 'Kawhmu Township');
insert into Township (division_id, name) values(15, 'Kayan Township');
insert into Township (division_id, name) values(15, 'Kungyangon Township');
insert into Township (division_id, name) values(15, 'Kyauktan Township');
insert into Township (division_id, name) values(15, 'Thanlyin Township');
insert into Township (division_id, name) values(15, 'Thongwa Township');
insert into Township (division_id, name) values(15, 'Twante Township');
insert into Township (division_id, name) values(15, 'Ahlon Township');
insert into Township (division_id, name) values(15, 'Bahan Township');
insert into Township (division_id, name) values(15, 'Dagon Township');
insert into Township (division_id, name) values(15, 'Kyauktada Township');
insert into Township (division_id, name) values(15, 'Kyimyindaing Township');
insert into Township (division_id, name) values(15, 'Lanmadaw Township');
insert into Township (division_id, name) values(15, 'Latha Township');
insert into Township (division_id, name) values(15, 'Pabedan Township');
insert into Township (division_id, name) values(15, 'Sanchaung Township');
insert into Township (division_id, name) values(15, 'Seikkan Township');
insert into Township (division_id, name) values(15, 'Hlaing Township');
insert into Township (division_id, name) values(15, 'Kamayut Township');
insert into Township (division_id, name) values(15, 'Mayangon Township');
